---@meta

---@class QBShared_Vehicle
---@field name string
---@field brand string
---@field model string
---@field price number
---@field category string
---@field categoryLabel string
---@field hash number
---@field shop string